version: "3.5" 
services: 
  postgres: 
    image: postgres
    env_file: 
      - ./config/pg-env.list
    volumes: 
      - pgvolume:/var/lib/postgresql/data 
    ports: 
      - "5432:5432" 
    networks: 
      - pgnetwork 

  pgadmin: 
    # TODO move to normal pgadmin image
    image: crunchydata/crunchy-pgadmin4:centos7-10.4-2.0.0 
    env_file: 
      - ./config/pgadmin-env.list 
    volumes: 
      - pga4volume:/var/lib/pgadmin 
    ports: 
      - "5050:5050" 
    networks: 
      - pgnetwork 
  
  my-golang-app:
    build: .
    env_file:
      - ./config/golang-env.list
    ports: 
      - "8080:8080"
    depends_on:
      - "postgres"
      - "pgadmin"
    command: ["./wait-for-it.sh", "db:5432", "-t", "3", "--", "app"]
    networks:
      - pgnetwork

networks: 
  pgnetwork:
    name: pgnetwork

volumes: 
  pgvolume:
    name: pgvolume
  pga4volume:
    name: pga4volume

