version: "3" 
services: 
  postgres: 
    image: crunchydata/crunchy-postgres:centos7-10.4-2.0.0 
    env_file: 
      - pg-env.list 
    volumes: 
      - pgvolume:/pgdata 
    ports: 
      - "5432:5432" 
    networks: 
      - pgnetwork 

  pgadmin: 
    image: crunchydata/crunchy-pgadmin4:centos7-10.4-2.0.0 
    env_file: 
      - pgadmin-env.list 
    volumes: 
      - pga4volume:/var/lib/pgadmin 
    ports: 
      - "5050:5050" 
    networks: 
      - pgnetwork 

networks: 
  pgnetwork:

volumes: 
  pgvolume:
  pga4volume:

